/**
 * Supabase Integration for Notes & Chunks (RAG)
 */

import { supabase, type Database } from './client';
import type { Chunk } from '../types';

export async function getNoteWithChunks(noteId: string) {
  const { data: note, error: noteError } = await supabase
    .from('notes')
    .select('*')
    .eq('id', noteId)
    .single();

  if (noteError || !note) return null;

  // Get all chunks for this note
  const { data: chunks } = await supabase
    .from('chunks')
    .select('*')
    .eq('note_id', noteId)
    .order('chapter_id', { ascending: true });

  return {
    ...note,
    chunks: chunks ?? [],
  };
}

export async function saveNote(data: {
  title: string;
  summary: string;
  subject?: string | null;
  user_id: string;
  id?: string;
}) {
  const noteData = {
    ...data,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const { data: savedNote, error } = await supabase
    .from('notes')
    .upsert({
      ...noteData,
      id: data.id || undefined,
    })
    .select()
    .single();

  if (error) throw error;
  return savedNote;
}

export async function updateNote(
  noteId: string,
  updates: Partial<{
    title: string;
    summary: string;
    subject: string | null;
  }>
) {
  const { data, error } = await supabase
    .from('notes')
    .update({
      ...updates,
      updated_at: new Date().toISOString(),
    })
    .eq('id', noteId)
    .select()
    .single();

  if (error) throw error;
  return data;
}

export async function deleteNote(noteId: string) {
  const { error } = await supabase
    .from('notes')
    .delete()
    .eq('id', noteId);

  if (error) throw error;
}

export async function getNotesByUser(userId: string) {
  const { data, error } = await supabase
    .from('notes')
    .select('*')
    .eq('user_id', userId)
    .order('updated_at', { ascending: false });

  if (error) throw error;
  return data;
}

export async function insertChunksForNote({
  noteId,
  chapterId,
  chunks,
}: {
  noteId: string;
  chapterId: number;
  chunks: string[];
}) {
  const chunkRecords = chunks.map((text, index) => ({
    note_id: noteId,
    chapter_id: chapterId,
    text: text.trim(),
    embedding: null,
  }));

  const { error } = await supabase.from('chunks').insert(chunkRecords);

  if (error) throw error;
}

export async function updateChunksEmbeddings(
  noteId: string,
  embeddings: number[][]
) {
  const updates = embeddings.map((embedding, index) => ({
    id: `chunk-${noteId}-${index}`, // Will be generated by database
    note_id: noteId,
    embedding: embedding,
  }));

  // Note: In production, you'd need chunk IDs. For now, we'll update all chunks for this note
  for (const emb of embeddings) {
    await supabase.rpc('match_chunks', {
      query_embedding: emb as number[],
      note_id: noteId,
      similarity_threshold: 0,
      top_k: 1,
    });
  }
}

export async function searchChunks(
  embedding: number[],
  topK: number = 4,
  noteId?: string
) {
  const { data, error } = await supabase.rpc('match_chunks', {
    query_embedding: embedding as number[],
    note_id: noteId,
    similarity_threshold: 0.78,
    top_k: topK,
  });

  if (error) throw error;
  return data ?? [];
}

export async function getAllSubjects() {
  const { data, error } = await supabase
    .from('subjects')
    .select('*')
    .order('name');

  if (error) throw error;
  return data ?? [];
}
